# Generated by Django 3.0.3 on 2020-03-01 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=128, verbose_name='Ulica')),
                ('block_number', models.CharField(max_length=64, verbose_name='Nr domu')),
                ('flat_number', models.CharField(max_length=64, null=True, verbose_name='Nr mieszkania')),
                ('post_code', models.CharField(max_length=16, verbose_name='Kod pocztowy')),
                ('city', models.CharField(max_length=64, verbose_name='Miasto')),
                ('description', models.TextField(verbose_name='Opis mieszkania')),
            ],
        ),
    ]
