# Generated by Django 3.0.3 on 2020-03-01 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyRent', '0002_auto_20200301_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationDict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Operacja finansowa')),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data operacji')),
                ('value', models.FloatField(verbose_name='Kwota operacji')),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyRent.Agreement', verbose_name='Umowa najmu')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyRent.OperationDict', verbose_name='Typ operacji finansowej')),
            ],
        ),
    ]
