# Generated by Django 3.0.3 on 2020-03-03 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MyRent', '0005_auto_20200302_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationdict',
            name='plus_minus',
            field=models.SmallIntegerField(choices=[(1, 'PLUS'), (2, 'MINUS')], default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tenant',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User login'),
        ),
    ]
