# Generated by Django 3.0.3 on 2020-03-03 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyRent', '0006_auto_20200303_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='is_for_rent',
            field=models.BooleanField(default=True, verbose_name='Czy jest do wynajęcia'),
        ),
        migrations.AlterField(
            model_name='operationdict',
            name='plus_minus',
            field=models.SmallIntegerField(choices=[(1, 'PLUS'), (2, 'MINUS')], verbose_name='Wpływ na saldo rozliczeń'),
        ),
    ]
