# Generated by Django 3.0.3 on 2020-03-04 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyRent', '0008_auto_20200304_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='picture',
            field=models.ImageField(default='no-img.png', upload_to=''),
        ),
    ]
