# Generated by Django 3.0.3 on 2020-03-04 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyRent', '0009_auto_20200304_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='name',
        ),
        migrations.AddField(
            model_name='image',
            name='info',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Opis zdjęcia'),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='info',
            field=models.TextField(blank=True, null=True, verbose_name='Dodatkowe info'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='info',
            field=models.TextField(blank=True, null=True, verbose_name='Dodatkowe info'),
        ),
        migrations.AlterField(
            model_name='image',
            name='flat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyRent.Flat', verbose_name='Mieszkanie dot. zdjęcia'),
        ),
        migrations.AlterField(
            model_name='image',
            name='picture',
            field=models.ImageField(default='no-img.png', upload_to='', verbose_name='Zdjęcie'),
        ),
        migrations.AlterField(
            model_name='landlord',
            name='info',
            field=models.TextField(blank=True, null=True, verbose_name='Dodatkowe info'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='info',
            field=models.TextField(blank=True, null=True, verbose_name='Dodatkowe info'),
        ),
    ]
